- name: Launch PostgreSQL container
  docker_container:
    name: db
    image: ccao94/tp1-database:latest
    env:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: db
    networks:
      - name: app-network # Connect to shared network
    volumes:
      - "db-data:/var/lib/postgresql/data" # Persist database data
    state: started
    restart_policy: always
