version: '3.8'

services:
  backend:
    build: ./backend 
    container_name: api 
    restart: unless-stopped
    networks:
      - app-network 
    depends_on:
      - database 
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/db
      - SPRING_DATASOURCE_USERNAME=usr
      - SPRING_DATASOURCE_PASSWORD=pwd

  database:
    build: ./database
    container_name: db
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
    volumes:
      - db-data:/var/lib/postgresql/data

  httpd:
    build: ./httpd
    container_name: web
    restart: unless-stopped
    ports:
      - "80:80"    
    networks:
      - app-network
    depends_on:
      - backend 

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local