- name: Launch Apache reverse proxy
  docker_container:
    name: web # Container name exposed on host port 80
    image: ccao94/tp1-httpd:latest # Corrected image name
    networks:
      - name: proxy-network # Connect Apache only to proxy network
    published_ports:
      - "80:80" # Expose Apache to host