- name: Launch backend container
  docker_container:
    name: backend
    image: ccao94/tp1-backend:latest
    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db # Connect to PostgreSQL
      SPRING_DATASOURCE_USERNAME: usr
      SPRING_DATASOURCE_PASSWORD: pwd
    networks:
      - name: app-network
    published_ports:
      - "8080:8080" # Expose backend port internally (optional)
    state: started
    restart_policy: always
