name: CI/CD devops 2025

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and test with Maven
        run: mvn clean verify --file backend/pom.xml

  build-and-push-images:
    # Ce job ne démarre que si 'test-backend' a réussi
    needs: test-backend
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend # Chemin vers le Dockerfile du backend
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp1-backend:latest
          # Ne "push" que si on est sur la branche master
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: Build and push database image
        uses: docker/build-push-action@v6
        with:
          context: ./database # Chemin vers le Dockerfile de la DB
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp1-database:latest
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: Build and push httpd image
        uses: docker/build-push-action@v6
        with:
          context: ./httpd # Chemin vers le Dockerfile d'apache
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp1-httpd:latest
          push: ${{ github.ref == 'refs/heads/master' }}