name: CI/CD devops 2025
on:
  #to begin you want to launch this job in main and develop
  push:
    branches:
      - master
      - develop
  pull_request:

 #defines all the jobs that will run
jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
     #checkout your github code using actions/checkout@v4
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and test with Maven
        run: mvn clean verify --file backend/pom.xml

     #run SonarCloud analysis
      - name: SonarCloud Scan
        # This command runs after the tests and sends the report to SonarCloud, we use secrets for the token and provide the project keys
        run: >-
          mvn -B verify sonar:sonar
          -Dsonar.projectKey=d6b9f7f6e4f6e9f9d102461839e766ded82623fb
          -Dsonar.organization=0f7c54f37ce0a41a1fdcb951aec1b84503d6f283
          -Dsonar.host.url=https://sonarcloud.io0f7c54f37ce0a41a1fdcb951aec1b84503d6f283
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          --file backend/pom.xml

  # Build and Push Docker images
  build-and-push-images:
  #this only starts if 'test-backend' job was successful
    needs: test-backend
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend 
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp1-backend:latest
          #only push if we are on the 'master' branch
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: Build and push database image
        uses: docker/build-push-action@v6
        with:
          context: ./database
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp1-database:latest
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: Build and push httpd image
        uses: docker/build-push-action@v6
        with:
          context: ./httpd 
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp1-httpd:latest
          push: ${{ github.ref == 'refs/heads/master' }}
