name: CI/CD devops 2025
on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  # Build, Test, and Analyze code
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build, test with Maven
        run: mvn clean verify
        working-directory: ./backend

      - name: SonarCloud Scan
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=ccao94_tp1-docker -Dsonar.organization=ccao94 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        working-directory: ./backend

  # Build and Push Docker images (only for master branch)
  build-and-push-images:
    needs: test-backend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp1-backend:latest
          push: true

      - name: Build and push database image
        uses: docker/build-push-action@v6
        with:
          context: ./database
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp1-database:latest
          push: true

      - name: Build and push httpd image
        uses: docker/build-push-action@v6
        with:
          context: ./httpd
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp1-httpd:latest
          push: true

  # Deploy using Ansible (only for master branch)
  deploy-with-ansible:
    needs: build-and-push-images
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible sshpass

      - name: Prepare SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_ansible
          chmod 600 ~/.ssh/id_rsa_ansible

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H cao.cao.takima.cloud >> ~/.ssh/known_hosts

      - name: Prepare Vault Password File
        run: echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > vault_pass.txt

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventories/setup.yml ansible/playbook.yml --vault-password-file ./vault_pass.txt --extra-vars "ansible_ssh_private_key_file=~/.ssh/id_rsa_ansible"

      - name: Clean up temporary files
        if: always()
        run: |
          rm -f vault_pass.txt
          rm -f ~/.ssh/id_rsa_ansible
